[package]
name = "tim-rs"
version = "0.1.0"
edition = "2021"

[dependencies]

axum = { version = "*", features = ["ws"] }
futures = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
tokio = { version = "*", features = ["rt-multi-thread"] }

